
CREATE VIEW V_TICKET AS

SELECT  T.ID 				AS "TICKET_ID", 
	T.VERSION			AS "VERSION",
	TA.NAME 			AS "ACTION", 	
	T.DESCRIPTION 			AS "DESCRIPTION", 
	S.STATUS 			AS "STATUS", 
	--Account Person Device details
	T.ACCOUNT_ID			AS "ACCOUNT_ID",
	U.FIRST_NAME			AS "FIRST_NAME",
	U.LAST_NAME			AS "LAST_NAME",
	DE.DEVICE_TYPE			AS "DEVICE",
	CG.USER_NAME			AS "CREATED_BY",
	AG.USER_NAME			AS "ASSIGNED_TO",	
	T.NOTES				AS "NOTES",
	L.LOCATION_NAME			AS "LOCATION",
	--More Fields
	TA.DESCRIPTION 			AS "ACTION_DESCRIPTION", 	
	T.PERSON_ID			AS "PERSON_ID",
	T.PERSON_DEVICE_ID		AS "PERSON_DEVICE_ID",
	T.ACTION_ID			AS "ACTION_ID",
	T.STATUS_ID			AS "STATUS_ID",
	T.OFFICE_LOCATION_ID		AS "OFFICE_LOCATION_ID",
	T.CREATED_AGENT_ID		AS "CREATED_AGENT_ID",
	T.ASSIGNED_AGENT_ID		AS "ASSIGNED_AGENT_ID"
FROM 	TICKET T,
	ACCOUNT A,
	PERSON U,
	PERSON_DEVICE D,
	DEVICE DE,
	TICKET_ACTION TA,
	TICKET_STATUS S,
	OFFICE_LOCATION L,
	AGENT AG,
	AGENT CG
WHERE 	1=1
AND	T.ACCOUNT_ID = A.ID
AND	T.PERSON_ID = U.ID
AND	T.PERSON_DEVICE_ID = D.ID
AND 	D.DEVICE_ID = DE.ID
AND	T.ACTION_ID = TA.ID
AND	T.STATUS_ID = S.ID
AND	T.OFFICE_LOCATION_ID = L.ID
AND	T.CREATED_AGENT_ID = AG.ID
AND	T.ASSIGNED_AGENT_ID = CG.ID

	