
DROP TABLE IF EXISTS OFFICE_LOCATION CASCADE;
DROP TABLE IF EXISTS TICKET_STATUS CASCADE;
DROP TABLE IF EXISTS TICKET_ACTION CASCADE;
DROP TABLE IF EXISTS ACCOUNT CASCADE;
DROP TABLE IF EXISTS PERSON CASCADE;
DROP TABLE IF EXISTS DEVICE CASCADE;
DROP TABLE IF EXISTS FILTER CASCADE;
DROP TABLE IF EXISTS PERSON_DEVICE CASCADE;
DROP TABLE IF EXISTS TICKET CASCADE;
DROP TABLE IF EXISTS AGENT CASCADE;



CREATE TABLE OFFICE_LOCATION
(
	ID				SERIAL PRIMARY KEY,
	LOCATION_NAME			VARCHAR(60),
	DESCRIPTION			VARCHAR(60),
	ADDRESS 			VARCHAR(60),
	CITY				VARCHAR(30),
	STATE_CD			VARCHAR(20),
	ZIP				VARCHAR(20),
	COUNTRY				VARCHAR(30),
	PHONE				VARCHAR(20),
	FAX				VARCHAR(20),
	NOTES				VARCHAR(255),
	HOURS				VARCHAR(255),
	EMAIL				VARCHAR(60)
);


CREATE TABLE TICKET_STATUS
(
	ID				SERIAL PRIMARY KEY,
	STATUS				VARCHAR(30),
	DESCRIPTION			VARCHAR(60)
);


CREATE TABLE TICKET_ACTION
(
	ID				SERIAL PRIMARY KEY,
	NAME				VARCHAR(60),
	CATEGORY			VARCHAR(60),
	DESCRIPTION			VARCHAR(60),
	WIKI_LINK			VARCHAR(60),
	NOTES				VARCHAR(255)
);


CREATE TABLE ACCOUNT
(
	ID				SERIAL PRIMARY KEY,
	FIRST_NAME			VARCHAR(30),
	LAST_NAME			VARCHAR(30),
	ADDRESS 			VARCHAR(30),
	CITY				VARCHAR(30),
	STATE_CD			VARCHAR(6),
	ZIP				VARCHAR(10),
	EMAIL				VARCHAR(60),
	PHONE				VARCHAR(20) UNIQUE,
	MOBILE_PHONE			VARCHAR(20),
	NOTES				VARCHAR(255),
	OFFICE_LOCATION_ID		INT REFERENCES OFFICE_LOCATION ON DELETE RESTRICT,
	PROTECTEDFLAG			INT
);


CREATE TABLE PERSON
(
	ID				SERIAL PRIMARY KEY,
	FIRST_NAME			VARCHAR(30),
	LAST_NAME			VARCHAR(30),
	ACCOUNT_ID			INT REFERENCES ACCOUNT ON DELETE CASCADE,
	GENDER				VARCHAR(2),
	MARRIED				VARCHAR(4),
	EMAIL				VARCHAR(60),
	PHONE				VARCHAR(20),
	MOBILE_PHONE			VARCHAR(20),
	NOTES				VARCHAR(255)
);


CREATE TABLE DEVICE
(
	ID				SERIAL PRIMARY KEY,
	DEVICE_TYPE			VARCHAR(30),
	MANUFACTURER			VARCHAR(120),
	MODEL				VARCHAR(120),
	OS 				VARCHAR(120),
	BROWSER				VARCHAR(120),
	NOTES				VARCHAR(255)
);


CREATE TABLE FILTER
(
	ID				SERIAL PRIMARY KEY,
	PROVIDER			VARCHAR(120),
	URL				VARCHAR(120),
	NOTES				VARCHAR(255)
);


CREATE TABLE PERSON_DEVICE
(
	ID				SERIAL PRIMARY KEY,
	PERSON_ID			INT REFERENCES PERSON ON DELETE CASCADE,
	DEVICE_ID			INT REFERENCES DEVICE ON DELETE RESTRICT,
	USER_NAME			VARCHAR(120),
	PASSWORD			VARCHAR(120),
	FILTER_ID			INT REFERENCES FILTER ON DELETE RESTRICT,
	FILTER_USER_NAME		VARCHAR(120),
	FILTER_PASSWORD			VARCHAR(120),
	NOTES				VARCHAR(255)
);


CREATE TABLE AGENT
(
	ID				SERIAL PRIMARY KEY,
	FIRST_NAME			VARCHAR(30),
	LAST_NAME			VARCHAR(30),
	USER_NAME			VARCHAR(30) UNIQUE NOT NULL,
	PASSWORD			VARCHAR(30),
	ADDRESS 			VARCHAR(30),
	CITY				VARCHAR(30),
	STATE_CD			VARCHAR(6),
	ZIP				VARCHAR(10),
	COUNTRY				VARCHAR(20),
	EMAIL				VARCHAR(60),
	PHONE				VARCHAR(20),
	MOBILE_PHONE			VARCHAR(20),
	NOTES				VARCHAR(255),
	OFFICE_LOCATION_ID		INT REFERENCES OFFICE_LOCATION ON DELETE RESTRICT
);



CREATE TABLE TICKET
(
	ID				SERIAL PRIMARY KEY,
	VERSION				INT,
	ACCOUNT_ID			INT REFERENCES ACCOUNT ON DELETE CASCADE,
	PERSON_ID			INT REFERENCES PERSON ON DELETE CASCADE,
	PERSON_DEVICE_ID		INT REFERENCES PERSON_DEVICE ON DELETE CASCADE,
	ACTION_ID			INT REFERENCES TICKET_ACTION ON DELETE RESTRICT,
	STATUS_ID			INT REFERENCES TICKET_STATUS ON DELETE RESTRICT,
	DESCRIPTION			VARCHAR(60),
	OFFICE_LOCATION_ID		INT REFERENCES OFFICE_LOCATION ON DELETE RESTRICT,
	NOTES				VARCHAR(255),
	CREATED_AGENT_ID		INT REFERENCES AGENT ON DELETE RESTRICT,
	ASSIGNED_AGENT_ID		INT REFERENCES AGENT ON DELETE RESTRICT
);


/*********************************************************************************
 *
 *			VIEWS
 * 
 *********************************************************************************/
 
CREATE VIEW V_TICKET AS
SELECT	T.ID 				AS "TICKET_ID",
 	T.VERSION			AS "VERSION",
 	TA.NAME 			AS "ACTION", 	
 	T.DESCRIPTION 			AS "DESCRIPTION",
 	S.STATUS 			AS "STATUS",
 	T.ACCOUNT_ID			AS "ACCOUNT_ID",
 	U.FIRST_NAME			AS "FIRST_NAME",
 	U.LAST_NAME			AS "LAST_NAME",
 	DE.DEVICE_TYPE			AS "DEVICE",
 	CG.USER_NAME			AS "CREATED_BY",
 	AG.USER_NAME			AS "ASSIGNED_TO",
 	T.NOTES				AS "NOTES",
 	L.LOCATION_NAME			AS "LOCATION",
 	TA.DESCRIPTION 			AS "ACTION_DESCRIPTION",
 	T.PERSON_ID			AS "PERSON_ID",
 	T.PERSON_DEVICE_ID		AS "PERSON_DEVICE_ID",
 	T.ACTION_ID			AS "ACTION_ID",
 	T.STATUS_ID			AS "STATUS_ID",
 	T.OFFICE_LOCATION_ID		AS "OFFICE_LOCATION_ID",
 	T.CREATED_AGENT_ID		AS "CREATED_AGENT_ID",
 	T.ASSIGNED_AGENT_ID		AS "ASSIGNED_AGENT_ID"
FROM 	TICKET T,
 	ACCOUNT A,
 	PERSON U,
 	PERSON_DEVICE D,
 	DEVICE DE,
 	TICKET_ACTION TA,
 	TICKET_STATUS S,
 	OFFICE_LOCATION L,
 	AGENT AG,
 	AGENT CG
WHERE	T.ACCOUNT_ID = A.ID
AND	T.PERSON_ID = U.ID
AND	T.PERSON_DEVICE_ID = D.ID
AND 	D.DEVICE_ID = DE.ID
AND	T.ACTION_ID = TA.ID
AND	T.STATUS_ID = S.ID
AND	T.OFFICE_LOCATION_ID = L.ID
AND	T.CREATED_AGENT_ID = AG.ID
AND	T.ASSIGNED_AGENT_ID = CG.ID
 
 