
CREATE SEQUENCE account_id_seq start 1
    increment 1
    NO MAXVALUE
    CACHE 1;		
	
--DROP TABLE ACCOUNT;	

CREATE TABLE ACCOUNT
(	
ID						INT NOT NULL DEFAULT nextval('account_id_seq'),
FIRST_NAME				VARCHAR(30), 
LAST_NAME				VARCHAR(30),
ADDRESS 				VARCHAR(30),
CITY					VARCHAR(30), 
STATE_CD				VARCHAR(6),
ZIP						VARCHAR(10),
EMAIL					VARCHAR(60),
PHONE					VARCHAR(20),
MOBILE_PHONE			VARCHAR(20),
NOTES					VARCHAR(255),
OFFICE_LOCATION_ID		INT,
PROTECTEDFLAG			INT
);
ALTER SEQUENCE account_id_seq OWNED BY ACCOUNT.ID;
