

CREATE SEQUENCE agent_id_seq start 1
    increment 1
    NO MAXVALUE
    CACHE 1;	

--DROP TABLE AGENT;

CREATE TABLE AGENT
(
ID						INT NOT NULL DEFAULT nextval('agent_id_seq'),
FIRST_NAME				VARCHAR(30), 
LAST_NAME				VARCHAR(30),
USER_NAME				VARCHAR(30),
PASSWORD			    VARCHAR(30),
ADDRESS 				VARCHAR(30),
CITY					VARCHAR(30), 
STATE_CD				VARCHAR(6),
ZIP						VARCHAR(10),
COUNTRY					VARCHAR(20),
EMAIL					VARCHAR(60),
PHONE					VARCHAR(20),
MOBILE_PHONE			VARCHAR(20),
NOTES					VARCHAR(255),
OFFICE_LOCATION_ID		INT
);
ALTER SEQUENCE agent_id_seq OWNED BY AGENT.ID;