	
DROP TABLE IF EXISTS OFFICE_LOCATION CASCADE;	
	
CREATE TABLE OFFICE_LOCATION
(
ID						SERIAL PRIMARY KEY,
LOCATION_NAME			VARCHAR(60),
DESCRIPTION				VARCHAR(60),			
ADDRESS 				VARCHAR(30),
CITY					VARCHAR(30), 
STATE_CD				VARCHAR(20),
ZIP						VARCHAR(20),
COUNTRY					VARCHAR(30), 
PHONE					VARCHAR(20),
FAX						VARCHAR(20),
NOTES					VARCHAR(255),
HOURS					VARCHAR(255),
EMAIL					VARCHAR(60)
);

DROP TABLE IF EXISTS TICKET_STATUS CASCADE;
	
CREATE TABLE TICKET_STATUS
(
ID					SERIAL PRIMARY KEY,
STATUS				VARCHAR(30),
DESCRIPTION			VARCHAR(30)
);
	
DROP TABLE IF EXISTS TICKET_ACTION CASCADE;
	
CREATE TABLE TICKET_ACTION
(
ID						SERIAL PRIMARY KEY,
NAME					VARCHAR(60),
CATEGORY				VARCHAR(60),
DESCRIPTION				VARCHAR(60),
WIKI_LINK				VARCHAR(60),
NOTES					VARCHAR(255)
);

DROP TABLE IF EXISTS ACCOUNT CASCADE;

CREATE TABLE ACCOUNT
(	
ID						SERIAL PRIMARY KEY,
FIRST_NAME				VARCHAR(30), 
LAST_NAME				VARCHAR(30),
ADDRESS 				VARCHAR(30),
CITY					VARCHAR(30), 
STATE_CD				VARCHAR(6),
ZIP						VARCHAR(10),
EMAIL					VARCHAR(60),
PHONE					VARCHAR(20),
MOBILE_PHONE			VARCHAR(20),
NOTES					VARCHAR(255),
OFFICE_LOCATION_ID		INT REFERENCES OFFICE_LOCATION ON DELETE RESTRICT,
PROTECTEDFLAG			INT
);

DROP TABLE IF EXISTS PERSON CASCADE;

CREATE TABLE PERSON
(
ID						SERIAL PRIMARY KEY,
FIRST_NAME				VARCHAR(30), 
LAST_NAME				VARCHAR(30),
ACCOUNT_ID				INT REFERENCES ACCOUNT ON DELETE CASCADE,
GENDER					VARCHAR(2),
MARRIED					VARCHAR(4),
EMAIL					VARCHAR(60),
PHONE					VARCHAR(20),
MOBILE_PHONE			VARCHAR(20),
NOTES					VARCHAR(255)				
);	

DROP TABLE IF EXISTS DEVICE CASCADE;
	
CREATE TABLE DEVICE
(
ID						SERIAL PRIMARY KEY,
DEVICE_TYPE				VARCHAR(30),
MANUFACTURER			VARCHAR(120),
MODEL					VARCHAR(120),
OS 						VARCHAR(120),
BROWSER					VARCHAR(120),
NOTES					VARCHAR(255)	
);	
	
DROP TABLE IF EXISTS FILTER CASCADE;
	
CREATE TABLE FILTER
(
ID						SERIAL PRIMARY KEY,
PROVIDER				VARCHAR(120),
URL						VARCHAR(120),
NOTES					VARCHAR(255)	
);	
	
DROP TABLE IF EXISTS PERSON_DEVICE CASCADE;
	
CREATE TABLE PERSON_DEVICE
(
ID						SERIAL PRIMARY KEY,
PERSON_ID				INT REFERENCES PERSON ON DELETE CASCADE,
DEVICE_ID				INT REFERENCES DEVICE ON DELETE RESTRICT,
USER_NAME				VARCHAR(120),
PASSWORD				VARCHAR(120),
FILTER_ID				INT REFERENCES FILTER ON DELETE RESTRICT,
FILTER_USER_NAME		VARCHAR(120),
FILTER_PASSWORD			VARCHAR(120),
NOTES					VARCHAR(255)	
);	

DROP TABLE IF EXISTS AGENT CASCADE;

CREATE TABLE AGENT
(
ID						SERIAL PRIMARY KEY,
FIRST_NAME				VARCHAR(30), 
LAST_NAME				VARCHAR(30),
USER_NAME				VARCHAR(30),
PASSWORD			    VARCHAR(30),
ADDRESS 				VARCHAR(30),
CITY					VARCHAR(30), 
STATE_CD				VARCHAR(6),
ZIP						VARCHAR(10),
COUNTRY					VARCHAR(20),
EMAIL					VARCHAR(60),
PHONE					VARCHAR(20),
MOBILE_PHONE			VARCHAR(20),
NOTES					VARCHAR(255),
OFFICE_LOCATION_ID		INT REFERENCES OFFICE_LOCATION ON DELETE RESTRICT
);
	

DROP TABLE IF EXISTS TICKET CASCADE;	

CREATE TABLE TICKET
(
ID						SERIAL PRIMARY KEY,
VERSION					INT,
ACCOUNT_ID				INT REFERENCES ACCOUNT ON DELETE CASCADE,
PERSON_ID				INT REFERENCES PERSON ON DELETE CASCADE,
PERSON_DEVICE_ID		INT REFERENCES PERSON_DEVICE ON DELETE CASCADE,
ACTION_ID				INT REFERENCES TICKET_ACTION ON DELETE RESTRICT,
STATUS_ID				INT REFERENCES TICKET_STATUS ON DELETE RESTRICT,
DESCRIPTION				VARCHAR(60),
OFFICE_LOCATION_ID		INT REFERENCES OFFICE_LOCATION ON DELETE RESTRICT,
NOTES					VARCHAR(255),
CREATED_AGENT_ID		INT REFERENCES AGENT ON DELETE RESTRICT,
ASSIGNED_AGENT_ID		INT REFERENCES AGENT ON DELETE RESTRICT
);

