


	
CREATE SEQUENCE ticket_id_seq start 1
    increment 1
    NO MAXVALUE
    CACHE 1;	
	
--DROP TABLE TICKET;	

CREATE TABLE TICKET
(
ID				INT NOT NULL DEFAULT nextval('ticket_id_seq'),
VERSION					INT,
ACCOUNT_ID				INT,
PERSON_ID				INT,
PERSON_DEVICE_ID		INT,
ACTION_ID				INT,
STATUS_ID				INT,
DESCRIPTION				VARCHAR(60),
OFFICE_LOCATION_ID		INT,
NOTES					VARCHAR(255),
CREATED_AGENT_ID		INT,
ASSIGNED_AGENT_ID		INT
);
ALTER SEQUENCE ticket_id_seq OWNED BY TICKET.ID;



CREATE SEQUENCE device_id_seq start 1
    increment 1
    NO MAXVALUE
    CACHE 1;	
	
--DROP TABLE DEVICE;
	
CREATE TABLE DEVICE
(
ID						INT NOT NULL DEFAULT nextval('device_id_seq'),
DEVICE_TYPE				VARCHAR(30),
MANUFACTURER			VARCHAR(120),
MODEL					VARCHAR(120),
OS 						VARCHAR(120),
BROWSER					VARCHAR(120),
NOTES					VARCHAR(255)	
);	
ALTER SEQUENCE device_id_seq OWNED BY DEVICE.ID;




CREATE SEQUENCE person_device_id_seq start 1
    increment 1
    NO MAXVALUE
    CACHE 1;	
	
--DROP TABLE PERSON_DEVICE;
	
CREATE TABLE PERSON_DEVICE
(
ID						INT NOT NULL DEFAULT nextval('person_device_id_seq'),
PERSON_ID				INT,
DEVICE_ID				INT,
USER_NAME				VARCHAR(120),
PASSWORD				VARCHAR(120),
FILTER_ID				INT,
FILTER_USER_NAME		VARCHAR(120),
FILTER_PASSWORD			VARCHAR(120),
NOTES					VARCHAR(255)	
);	
ALTER SEQUENCE person_device_id_seq OWNED BY PERSON_DEVICE.ID;



CREATE SEQUENCE person_id_seq start 1
    increment 1
    NO MAXVALUE
    CACHE 1;		
--DROP TABLE PERSON;

CREATE TABLE PERSON
(
ID						INT NOT NULL DEFAULT nextval('person_id_seq'),
FIRST_NAME				VARCHAR(30), 
LAST_NAME				VARCHAR(30),
ACCOUNT_ID				INT,
GENDER					VARCHAR(2),
MARRIED					VARCHAR(4),
EMAIL					VARCHAR(60),
PHONE					VARCHAR(20),
MOBILE_PHONE			VARCHAR(20),
NOTES					VARCHAR(255)				
);	
ALTER SEQUENCE PERSON_id_seq OWNED BY PERSON.ID;



CREATE SEQUENCE PERSON_DEVICE_id_seq start 1
    increment 1
    NO MAXVALUE
    CACHE 1;	
	
--DROP TABLE PERSON_DEVICE;
	
CREATE TABLE PERSON_DEVICE
(
ID						INT NOT NULL DEFAULT nextval('PERSON_DEVICE_id_seq'),
TAG_USER_ID				INT,
DEVICE_ID				INT,
USER_NAME				VARCHAR(120),
PASSWORD				VARCHAR(120),
FILTER_ID				INT,
FILTER_USER_NAME		VARCHAR(120),
FILTER_PASSWORD			VARCHAR(120),
NOTES					VARCHAR(255)	
);	
ALTER SEQUENCE PERSON_DEVICE_id_seq OWNED BY PERSON_DEVICE.ID;



CREATE SEQUENCE agent_id_seq start 1
    increment 1
    NO MAXVALUE
    CACHE 1;	

--DROP TABLE AGENT;

CREATE TABLE AGENT
(
ID						INT NOT NULL DEFAULT nextval('agent_id_seq'),
FIRST_NAME				VARCHAR(30), 
LAST_NAME				VARCHAR(30),
USER_NAME				VARCHAR(30),
PASSWORD			    VARCHAR(30),
ADDRESS 				VARCHAR(30),
CITY					VARCHAR(30), 
STATE_CD				VARCHAR(6),
ZIP						VARCHAR(10),
COUNTRY					VARCHAR(20),
EMAIL					VARCHAR(60),
PHONE					VARCHAR(20),
MOBILE_PHONE			VARCHAR(20),
NOTES					VARCHAR(255),
OFFICE_LOCATION_ID		INT
);
ALTER SEQUENCE agent_id_seq OWNED BY AGENT.ID;



CREATE SEQUENCE filter_id_seq start 1
    increment 1
    NO MAXVALUE
    CACHE 1;	
	
--DROP TABLE FILTER;
	
CREATE TABLE FILTER
(
ID						INT NOT NULL DEFAULT nextval('filter_id_seq'),
PROVIDER				VARCHAR(120),
URL						VARCHAR(120),
NOTES					VARCHAR(255)	
);	
ALTER SEQUENCE filter_id_seq OWNED BY FILTER.ID;



CREATE SEQUENCE ticket_status_id_seq start 1
    increment 1
    NO MAXVALUE
    CACHE 1;		
	
--DROP TABLE TICKET_STATUS;
	
CREATE TABLE TICKET_STATUS
(
ID				INT NOT NULL DEFAULT nextval('ticket_status_id_seq'),
STATUS				VARCHAR(30),
DESCRIPTION			VARCHAR(30)
);
ALTER SEQUENCE ticket_status_id_seq OWNED BY TICKET_STATUS.ID;	


CREATE SEQUENCE office_location_id_seq start 1
    increment 1
    NO MAXVALUE
    CACHE 1;	

	--DROP TABLE OFFICE_LOCATION;
	
CREATE TABLE OFFICE_LOCATION
(
ID				INT NOT NULL DEFAULT nextval('office_location_id_seq'),
LOCATION_NAME			VARCHAR(60),
DESCRIPTION				VARCHAR(60),			
ADDRESS 				VARCHAR(30),
CITY					VARCHAR(30), 
STATE_CD				VARCHAR(20),
ZIP						VARCHAR(20),
COUNTRY					VARCHAR(30), 
PHONE					VARCHAR(20),
FAX						VARCHAR(20),
NOTES					VARCHAR(255),
HOURS					VARCHAR(255),
EMAIL					VARCHAR(60)
);
ALTER SEQUENCE office_location_id_seq OWNED BY OFFICE_LOCATION.ID;



CREATE SEQUENCE ticket_action_id_seq start 1
    increment 1
    NO MAXVALUE
    CACHE 1;	
	
--DROP TABLE TICKET_ACTION;
	
CREATE TABLE TICKET_ACTION
(
ID						INT NOT NULL DEFAULT nextval('ticket_action_id_seq'),
NAME					VARCHAR(60),
CATEGORY				VARCHAR(60),
DESCRIPTION				VARCHAR(60),
WIKI_LINK				VARCHAR(60),
NOTES					VARCHAR(255)
);
ALTER SEQUENCE ticket_action_id_seq OWNED BY TICKET_ACTION.ID;


CREATE SEQUENCE account_id_seq start 1
    increment 1
    NO MAXVALUE
    CACHE 1;		
	
--DROP TABLE ACCOUNT;	

CREATE TABLE ACCOUNT
(	
ID						INT NOT NULL DEFAULT nextval('account_id_seq'),
FIRST_NAME				VARCHAR(30), 
LAST_NAME				VARCHAR(30),
ADDRESS 				VARCHAR(30),
CITY					VARCHAR(30), 
STATE_CD				VARCHAR(6),
ZIP						VARCHAR(10),
EMAIL					VARCHAR(60),
PHONE					VARCHAR(20),
MOBILE_PHONE			VARCHAR(20),
NOTES					VARCHAR(255),
OFFICE_LOCATION_ID		INT,
PROTECTEDFLAG			INT
);
ALTER SEQUENCE account_id_seq OWNED BY ACCOUNT.ID;



