

CREATE SEQUENCE filter_id_seq start 1
    increment 1
    NO MAXVALUE
    CACHE 1;	
	
--DROP TABLE FILTER;
	
CREATE TABLE FILTER
(
ID						INT NOT NULL DEFAULT nextval('filter_id_seq'),
PROVIDER				VARCHAR(120),
URL						VARCHAR(120),
NOTES					VARCHAR(255)	
);	
ALTER SEQUENCE filter_id_seq OWNED BY FILTER.ID;