
CREATE SEQUENCE office_location_id_seq start 1
    increment 1
    NO MAXVALUE
    CACHE 1;	

	--DROP TABLE OFFICE_LOCATION;
	
CREATE TABLE OFFICE_LOCATION
(
ID				INT NOT NULL DEFAULT nextval('office_location_id_seq'),
LOCATION_NAME			VARCHAR(60),
DESCRIPTION				VARCHAR(60),			
ADDRESS 				VARCHAR(30),
CITY					VARCHAR(30), 
STATE_CD				VARCHAR(20),
ZIP						VARCHAR(20),
COUNTRY					VARCHAR(30), 
PHONE					VARCHAR(20),
FAX						VARCHAR(20),
NOTES					VARCHAR(255),
HOURS					VARCHAR(255),
EMAIL					VARCHAR(60)
);
ALTER SEQUENCE office_location_id_seq OWNED BY OFFICE_LOCATION.ID;