

CREATE SEQUENCE person_device_id_seq start 1
    increment 1
    NO MAXVALUE
    CACHE 1;	
	
--DROP TABLE PERSON_DEVICE;
	
CREATE TABLE PERSON_DEVICE
(
ID						INT NOT NULL DEFAULT nextval('person_device_id_seq'),
PERSON_ID				INT,
DEVICE_ID				INT,
USER_NAME				VARCHAR(120),
PASSWORD				VARCHAR(120),
FILTER_ID				INT,
FILTER_USER_NAME		VARCHAR(120),
FILTER_PASSWORD			VARCHAR(120),
NOTES					VARCHAR(255)	
);	
ALTER SEQUENCE person_device_id_seq OWNED BY PERSON_DEVICE.ID;