
CREATE SEQUENCE tag_user_id_seq start 1
    increment 1
    NO MAXVALUE
    CACHE 1;		
--DROP TABLE TAG_USER;

CREATE TABLE TAG_USER
(
ID						INT NOT NULL DEFAULT nextval('tag_user_id_seq'),
FIRST_NAME				VARCHAR(30), 
LAST_NAME				VARCHAR(30),
ACCOUNT_ID				INT,
GENDER					VARCHAR(2),
MARRIED					VARCHAR(4),
EMAIL					VARCHAR(60),
PHONE					VARCHAR(20),
MOBILE_PHONE			VARCHAR(20),
NOTES					VARCHAR(255)				
);	
ALTER SEQUENCE tag_user_id_seq OWNED BY TAG_USER.ID;
