

CREATE SEQUENCE user_device_id_seq start 1
    increment 1
    NO MAXVALUE
    CACHE 1;	
	
--DROP TABLE USER_DEVICE;
	
CREATE TABLE USER_DEVICE
(
ID						INT NOT NULL DEFAULT nextval('user_device_id_seq'),
TAG_USER_ID				INT,
DEVICE_ID				INT,
USER_NAME				VARCHAR(120),
PASSWORD				VARCHAR(120),
FILTER_ID				INT,
FILTER_USER_NAME		VARCHAR(120),
FILTER_PASSWORD			VARCHAR(120),
NOTES					VARCHAR(255)	
);	
ALTER SEQUENCE user_device_id_seq OWNED BY USER_DEVICE.ID;